#!/bin/bash
SESSION="Amazon:1.1"

send_cmd() {
	tmux send-keys -t ${SESSION} "$1" Enter
}

for i in {1..10000000}; do
	# send_cmd "ace mw logging cli log 0 5 filter_test the example MAC address on wikipedia is 12:34:56:78:9A:BC"
	# send_cmd "python local_runner.py --m \"ACE_DTS_Optional_Privacyfilter_System\" --nobuild --noflash"
	# send_cmd "kvs set test_key$i 123456780000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	# send_cmd "python local_runner.py --m \"ACE_DTS_EntryDs_Integration\" --nobuild --noflash"
	# send_cmd "python local_runner.py --m \"ACE_DTS_DHA_Integration\" --nobuild --noflash"
	echo "The $i times test ..."
    send_cmd "reset reboot"
	# send_cmd "python3.6 local_runner.py -m ACE_MTS_WIFI_Openwrt_Connect_2g_Netimpairment_System --nobuild --noflash -i 8 --stop-after-first-failure --loops 50"
	# command_pid=$(ps -ef | grep "ACE_MTS_WIFI_Openwrt_Connect_2g_Netimpairment_System" | grep -v grep | awk '{print $2}')
	# echo "pid:$command_pid"
	# wait $command_pid
	sleep 10
done
